name: CI process

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache compose dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashfiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install composer dependecies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          mkdir tests/Unit

      - name: Run Tests
        run: php artisan test
